name = "SDPA"
uuid = "b9a10b5b-afa4-512f-a053-bb3d8080febc"
repo = "https://github.com/jump-dev/SDPA.jl.git"
version = "0.6.0"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
SDPA_jll = "7fc90fd6-dbef-5a6a-93f8-169f2a2e705b"

[compat]
CxxWrap = "0.17"
LinearAlgebra = "<0.0.1, 1.6"
MathOptInterface = "1"
SDPA_jll = "=700.301.800"
SparseArrays = "<0.0.1, 1.6"
Test = "<0.0.1, 1.6"
julia = "1.10"

[extras]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SparseArrays", "Test"]
